name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: Setup Node.js environment
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: "24.15.0"

      - name: Enable pnpm
        run: corepack enable

      - name: Get pnpm store directory
        id: pnpm-cache
        run: echo "store-path=$(pnpm store path --silent)" >> "$GITHUB_OUTPUT"

      - name: Cache dependencies
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        with:
          path: ${{ steps.pnpm-cache.outputs.store-path }}
          key: ${{ runner.OS }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.OS }}-pnpm-

      - run: pnpm install --frozen-lockfile
      - run: pnpm build
        env:
          PUBLIC_PATH: "/"

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@132898c54c57c7cc6b80eb3a89968de8fc283505 # releases/v3
        with:
          CLEAN: true
          SINGLE_COMMIT: true
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: dist # The folder the action should deploy.
